### ISSUE TITLE
PANTHER v11 attr.tab do not include all the PTN identifiers

### ISSUE THREAD

**Issue by selewis** [geneontology/panther-release-wrangling#1]
e.g. AN4 in PTHR10000

These are essential.

The missing PTNs from the files in:
http://pantherdata.usc.edu/PAINT_PANTHER11.0/books/PTHR*/attr.tab

**Comment by selewis** [comment]
From Huaiyu
"According to Xiaosong, the fixed attr files are on the server. I am sorry that I didn’t inform you earlier. Please check."

**Comment by selewis** [comment]
From me
"Is the server down today? I've tried a couple of times, but the connection keeps timing out. I've looked here:
http://data.pantherdb.org/
and here
http://data.pantherdb.org/PANTHER11.0/books"

**Comment by selewis** [comment]
@huaiyu

**Comment by selewis** [comment]
@huaiyu says: 
There is a server problem today, which impacts not only the paint files, but also our website. We filed a ticket to the USC IT department. They are looking into it right now. Sorry about the inconvenience.

**Comment by selewis** [comment]
@kltm and @cmungall 
Do you know Huaiyu's github id? I'm trying to get him to start using github.

**Comment by kltm** [comment]
If it's to be believed: https://github.com/orgs/geneontology/people as @huaiyumi , but not often used.

@selewis You should edit the tags you have above to the wrong user, as they will continue to get announcements due to the tag: https://github.com/geneontology/panther-release-wrangling/issues/1#issuecomment-260478808 https://github.com/geneontology/panther-release-wrangling/issues/1#issuecomment-260479437 .

**Comment by huaiyumi** [comment]
The USC IT fixed the problem and the PANTHER data server is up and running. Please try to see if the attribute tables can be accessed.

**Comment by selewis** [comment]
Hi @huaiyumi 
We're good. Closing this issue now. I'll let you know how the loading goes
